archives:
- files:
  - deploy/*
  - LICENSE
  - README.md
builds:
- dir: cmd/piv-agent
  goos:
  - darwin
  goarch:
  - amd64
  ldflags:
  - >
    -s -w -X main.date={{.Date}} -X "main.goVersion={{.Env.GOVERSION}}"
    -X main.shortCommit={{.ShortCommit}} -X main.version={{.Version}}
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_darwin_checksums.txt"
